Repository quarkusio/quarkus-platform, pull requests merged in 2021-11, with the labels that each got.

#380 Upgrade to Camel Quarkus 2.5.0
  generated-platform-project/quarkus-camel/bom/pom.xml
  generated-platform-project/quarkus-camel/integration-tests/camel-quarkus-integration-test-aws2-quarkus-client-grouped/pom.xml
  generated-platform-project/quarkus-camel/integration-tests/camel-quarkus-integration-test-ftp/pom.xml
  generated-platform-project/quarkus-camel/integration-tests/camel-quarkus-integration-test-telegram/pom.xml
  generated-platform-project/quarkus-camel/integration-tests/pom.xml
  generated-platform-project/quarkus-universe/bom/pom.xml
  pom.xml
Labels: release/noteworthy-feature

#384 remove invalid redhat-support values.
  src/main/resources/core/extensions-support-overrides.json
Labels: backport-2.2

#387 Upgrade to the platform generator 0.0.41
  pom.xml
Labels: backport-2.2

#383 Kogito 1.14.0.Final + OptaPlanner 8.14.0.Final
  generated-platform-project/quarkus-camel/bom/pom.xml
  generated-platform-project/quarkus-kogito/bom/pom.xml
  generated-platform-project/quarkus-kogito/integration-tests/kogito-quarkus-decisions-integration-test/pom.xml
  generated-platform-project/quarkus-optaplanner/bom/pom.xml
  generated-platform-project/quarkus-universe/bom/pom.xml
  pom.xml
Labels: backport

#389 Upgrade to the platform generator 0.0.42
  generated-platform-project/quarkus-kogito/bom/pom.xml
  generated-platform-project/quarkus-universe/bom/pom.xml
  pom.xml
Labels: backport
