Repository quarkusio/quarkus-platform, pull requests merged in 2022-04, with the labels that each got.

#514 Updating support level of extensions
  src/main/resources/core/extensions-support-overrides.json
Labels: backport

#517 Hide AmazonServices in rhproduct
  pom.xml
Labels: backport

#523 Removal of support of reactive-oracle-client
  src/main/resources/core/extensions-support-overrides.json
Labels: backport, backport-2.7

#526 adding metadata for extensions
  src/main/resources/core/extensions-support-overrides.json
Labels: backport-2.7
